"""IMAP access to Proton Mail through Proton Mail Bridge.

Proton Mail Bridge exposes a local IMAP server (default ``127.0.0.1:1143``).
Bridge v3 advertises STARTTLS on localhost (it manages the encrypted connection
to Proton's servers itself); ``security="starttls"`` is therefore the default
on accounts. Set ``security="ssl"`` for TLS-from-start (older Bridge versions)
or ``security="plain"`` to skip encryption (localhost only). For the local
self-signed certificate presented by the Bridge, TLS verification is disabled.
Authentication uses the Proton account address and a bridge-generated
password. This module wraps ``imaplib`` (stdlib) to provide the read
operations the MCP server exposes.

Every public function opens a fresh connection, performs its operation, then
logs out — keeping tools stateless and avoiding stale mailbox selections
between calls. Blocking ``imaplib`` calls run inside the MCP server's worker
threadpool, so synchronous code is fine here.
"""

from __future__ import annotations

import email
import email.utils
import imaplib
import re
import socket
import ssl
from dataclasses import dataclass
from email.header import decode_header, make_header
from email.message import Message
from typing import Iterable

from .config import Account


class ImapError(Exception):
    """Raised on IMAP connection or protocol errors surfaced to the agent."""


@dataclass
class FolderInfo:
    name: str
    delimiter: str
    flags: list[str]
    selectable: bool


@dataclass
class MessageSummary:
    uid: int
    folder: str
    subject: str
    sender: str
    to: str
    date: str
    flags: list[str]
    size: int
    snippet: str = ""


@dataclass
class GetMessage:
    uid: int
    folder: str
    headers: dict[str, str]
    body_text: str | None
    body_html: str | None
    attachments: list[dict]
    raw_size: int


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _ssl_context() -> ssl.SSLContext:
    """An SSL context that trusts the Bridge's local self-signed certificate.

    The Bridge certificate is local-only and ephemeral, so hostname verification
    is intentionally disabled for ``127.0.0.1``.
    """
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx


def _connect(account: Account) -> imaplib.IMAP4:
    """Open and authenticate an IMAP connection for ``account``.

    ``account.security`` selects how the connection is secured:

    - ``"starttls"`` (default): connect plaintext, then upgrade with STARTTLS —
      what Proton Mail Bridge v3 advertises for ``127.0.0.1:1143``.
    - ``"ssl"``: TLS from connection start (older Bridge versions).
    - ``"plain"``: no encryption (localhost only).
    """
    ctx = _ssl_context()
    try:
        if account.security == "ssl":
            conn = imaplib.IMAP4_SSL(
                host=account.host, port=account.port, ssl_context=ctx
            )
        else:
            conn = imaplib.IMAP4(host=account.host, port=account.port)
    except (OSError, socket.error) as exc:
        raise ImapError(
            f"Cannot connect to {account.host}:{account.port} for account "
            f"{account.name!r}. Is Proton Mail Bridge running? ({exc})"
        ) from exc

    if account.security == "starttls":
        try:
            typ, data = conn.starttls(ssl_context=ctx)
            if typ != "OK":
                raise ImapError(
                    f"STARTTLS upgrade failed for {account.name!r}: {typ} {data!r}"
                )
        except imaplib.IMAP4.error as exc:
            raise ImapError(
                f"STARTTLS upgrade failed for {account.name!r} on "
                f"{account.host}:{account.port}. ({exc})"
            ) from exc
        except (OSError, socket.error) as exc:
            raise ImapError(
                f"STARTTLS upgrade failed for {account.name!r}: {exc}"
            ) from exc

    try:
        typ, data = conn.login(account.username, account.password)
        if typ != "OK":
            raise ImapError(
                f"IMAP login failed for {account.username!r}: {typ} {data!r}"
            )
    except imaplib.IMAP4.error as exc:
        raise ImapError(
            f"IMAP login failed for {account.username!r} on account "
            f"{account.name!r}. Check that the username is the Proton address "
            f"and the password is the one generated by Proton Mail Bridge. ({exc})"
        ) from exc
    return conn


def _disconnect(conn: imaplib.IMAP4) -> None:
    """Best-effort close + logout so connections are never leaked."""
    try:
        try:
            conn.close()
        except imaplib.IMAP4.error:
            pass
        conn.logout()
    except (imaplib.IMAP4.error, OSError):
        pass


def _quote_mailbox(name: str) -> str:
    """Quote a mailbox name for SELECT, escaping embedded quotes/backslashes."""
    escaped = name.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _decode_header_value(value: str | None) -> str:
    """Decode an RFC 2047 encoded header into a single string."""
    if not value:
        return ""
    try:
        dec = decode_header(value)
        return str(make_header(dec))
    except Exception:
        return value


def _strip_tags(html: str) -> str:
    """Very small HTML->text for rendering when no text/plain exists."""
    text = re.sub(r"(?is)<(script|style).*?>.*?</\1>", "", html)
    text = re.sub(r"(?is)<br\s*/?>", "\n", text)
    text = re.sub(r"(?i)</p\s*>", "\n\n", text)
    text = re.sub(r"(?s)<[^>]+>", "", text)
    import html as html_mod

    return html_mod.unescape(text).strip()


_FOLDER_RE = re.compile(
    r'^\((?P<flags>[^)]*)\)\s+"(?P<delim>[^"]*)"\s+(?P<name>.*)$'
)


def _parse_mailbox_name(raw: str) -> str:
    """Unquote a mailbox name returned by LIST."""
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == '"' and raw[-1] == '"':
        return raw[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return raw


def _select(conn: imaplib.IMAP4, folder: str) -> int:
    """SELECT a mailbox and return the EXISTS message count."""
    typ, data = conn.select(_quote_mailbox(folder))
    if typ != "OK":
        raise ImapError(
            f"Could not select folder {folder!r}: {typ} {data!r}"
        )
    try:
        return int(data[0])
    except (ValueError, IndexError) as exc:
        raise ImapError(f"Unexpected SELECT response for {folder!r}: {data!r}") from exc


def _parse_meta(meta: bytes) -> dict:
    """Extract UID/FLAGS/INTERNALDATE/RFC822.SIZE from a FETCH metadata line."""
    s = meta.decode("utf-8", errors="replace")
    out: dict = {}
    m = re.search(r"\bUID\s+(\d+)", s)
    if m:
        out["uid"] = int(m.group(1))
    m = re.search(r"FLAGS\s+\(([^)]*)\)", s)
    if m:
        out["flags"] = [f.strip() for f in m.group(1).split() if f.strip()]
    else:
        out["flags"] = []
    m = re.search(r'INTERNALDATE\s+"([^"]*)"', s)
    if m:
        out["internaldate"] = m.group(1)
    m = re.search(r"RFC822\.SIZE\s+(\d+)", s)
    if m:
        out["size"] = int(m.group(1))
    return out


def _headers_to_dict(header_bytes: bytes) -> dict[str, str]:
    """Parse a block of raw headers into a dict of decoded header values."""
    msg = email.message_from_bytes(header_bytes)
    out: dict[str, str] = {}
    seen: dict[str, list[str]] = {}
    for key, value in msg.items():
        decoded = _decode_header_value(value)
        seen.setdefault(key.lower(), []).append(decoded)
    for key, values in seen.items():
        out[key] = ", ".join(values)
    return out


def _parse_fetch(data: Iterable) -> list[dict]:
    """Parse imaplib FETCH responses into per-message dicts.

    Each flagged message yields a tuple ``(meta_bytes, literal_bytes)`` where
    ``literal_bytes`` is the PEEKed header body. We pair them and also merge any
    continuation items, returning a list ordered by sequence number.
    """
    results: list[dict] = []
    for item in data:
        if isinstance(item, tuple) and len(item) == 2:
            meta, payload = item
            info = _parse_meta(meta)
            info["headers"] = payload
            results.append(info)
    return results


# ---------------------------------------------------------------------------
# operations
# ---------------------------------------------------------------------------

def list_folders(account: Account) -> list[FolderInfo]:
    """List all mailboxes available for ``account``."""
    conn = _connect(account)
    try:
        typ, data = conn.list()
        if typ != "OK":
            raise ImapError(f"LIST failed: {typ} {data!r}")
        folders: list[FolderInfo] = []
        for item in data:
            if isinstance(item, bytes):
                item = item.decode("utf-8", errors="replace")
            elif not isinstance(item, str):
                continue
            m = _FOLDER_RE.match(item.strip())
            if not m:
                continue
            flags = m.group("flags").split()
            name = _parse_mailbox_name(m.group("name"))
            selectable = r"\Noselect" not in flags
            folders.append(
                FolderInfo(
                    name=name,
                    delimiter=m.group("delim"),
                    flags=flags,
                    selectable=selectable,
                )
            )
        return folders
    finally:
        _disconnect(conn)


def _summaries_from_fetch(
    items: list[dict], folder: str, include_snippet: bool = False
) -> list[MessageSummary]:
    summaries: list[MessageSummary] = []
    for info in items:
        headers = _headers_to_dict(info.get("headers", b""))
        summaries.append(
            MessageSummary(
                uid=int(info.get("uid", 0) or 0),
                folder=folder,
                subject=headers.get("subject", "(no subject)") or "(no subject)",
                sender=headers.get("from", headers.get("sender", "")) or "",
                to=headers.get("to", "") or "",
                date=info.get("internaldate", headers.get("date", "")) or "",
                flags=info.get("flags", []),
                size=int(info.get("size", 0) or 0),
            )
        )
    # Newest first by INTERNALDATE, falling back to UID.
    summaries.sort(key=lambda s: s.date, reverse=True)
    return summaries


def list_messages(
    account: Account,
    folder: str = "INBOX",
    limit: int = 20,
    page: int = 0,
) -> list[MessageSummary]:
    """Return recent messages in ``folder``.

    Fetches a sequence window of ``limit`` envelopes (newest block first by
    IMAP sequence order), then re-sorts by internal date so the agent sees the
    most recent messages first. Pagination walks backwards through sequence
    space. Only envelope-level headers are transferred, regardless of mailbox
    size.
    """
    if limit <= 0:
        return []
    conn = _connect(account)
    try:
        exists = _select(conn, folder)
        if exists == 0:
            return []
        end = exists - page * limit
        start = max(1, end - limit + 1)
        if end < 1:
            return []
        range_str = f"{start}:{end}"
        typ, data = conn.fetch(
            range_str,
            "(UID FLAGS INTERNALDATE RFC822.SIZE "
            "BODY.PEEK[HEADER.FIELDS (SUBJECT FROM SENDER TO CC DATE MESSAGE-ID)])",
        )
        if typ != "OK":
            raise ImapError(f"FETCH failed: {typ} {data!r}")
        items = _parse_fetch(data)
        return _summaries_from_fetch(items, folder)
    finally:
        _disconnect(conn)


_CRITERIA_FIELDS = {
    "subject": "SUBJECT",
    "from": "FROM",
    "sender": "SENDER",
    "to": "TO",
    "cc": "CC",
    "bcc": "BCC",
    "body": "BODY",
    "text": "TEXT",
}


def search_messages(
    account: Account,
    query: str,
    folder: str = "INBOX",
    criteria: str = "subject",
    limit: int = 50,
) -> list[MessageSummary]:
    """Search messages in ``folder`` by a single IMAP field criterion.

    ``criteria`` is one of: subject, from, sender, to, cc, bcc, body, text.
    Results are capped at ``limit`` and sorted newest-first by internal date.
    """
    field = _CRITERIA_FIELDS.get(criteria.lower())
    if not field:
        raise ImapError(
            f"Unknown search criteria {criteria!r}. Valid: "
            + ", ".join(sorted(_CRITERIA_FIELDS))
        )
    if not query.strip():
        raise ImapError("Search query must not be empty.")

    # Escape for IMAP quoted-string: backslash and double-quote.
    escaped = query.replace("\\", "\\\\").replace('"', '\\"')
    quoted = f'"{escaped}"'

    conn = _connect(account)
    try:
        _select(conn, folder)
        typ, data = conn.search(None, field, quoted)
        if typ != "OK":
            raise ImapError(f"SEARCH failed: {typ} {data!r}")
        if not data or not data[0]:
            return []
        seq_nums = data[0].split()
        # SERVER side result; keep the newest `limit` by sequence then fetch.
        seq_nums = seq_nums[-limit:] if limit < len(seq_nums) else seq_nums
        range_str = ",".join(s.decode() if isinstance(s, bytes) else str(s) for s in seq_nums)
        if not range_str:
            return []
        typ, fdata = conn.fetch(
            range_str,
            "(UID FLAGS INTERNALDATE RFC822.SIZE "
            "BODY.PEEK[HEADER.FIELDS (SUBJECT FROM SENDER TO CC DATE MESSAGE-ID)])",
        )
        if typ != "OK":
            raise ImapError(f"FETCH after SEARCH failed: {typ} {fdata!r}")
        items = _parse_fetch(fdata)
        summaries = _summaries_from_fetch(items, folder)
        return summaries[:limit]
    finally:
        _disconnect(conn)


def _walk_message(msg: Message) -> tuple[str | None, str | None, list[dict]]:
    """Walk a multipart message returning (text_plain, text_html, attachments)."""
    text_plain: str | None = None
    text_html: str | None = None
    attachments: list[dict] = []

    for part in msg.walk():
        if part.is_multipart():
            continue
        content_disposition = (part.get_content_disposition() or "").lower()
        filename = part.get_filename()
        decoded_filename = _decode_header_value(filename) if filename else None

        if content_disposition == "attachment" or (
            filename and content_disposition not in ("inline", "")
        ):
            payload = part.get_payload(decode=True) or b""
            attachments.append(
                {
                    "filename": decoded_filename or "(unnamed)",
                    "content_type": part.get_content_type(),
                    "size": len(payload),
                }
            )
            continue

        ctype = part.get_content_type()
        if ctype == "text/plain" and text_plain is None:
            payload = part.get_payload(decode=True) or b""
            charset = part.get_content_charset() or "utf-8"
            try:
                text_plain = payload.decode(charset, errors="replace")
            except LookupError:
                text_plain = payload.decode("utf-8", errors="replace")
        elif ctype == "text/html" and text_html is None:
            payload = part.get_payload(decode=True) or b""
            charset = part.get_content_charset() or "utf-8"
            try:
                text_html = payload.decode(charset, errors="replace")
            except LookupError:
                text_html = payload.decode("utf-8", errors="replace")

    return text_plain, text_html, attachments


def get_message(account: Account, uid: int, folder: str = "INBOX") -> GetMessage:
    """Fetch a full message by UID and parse headers, body, and attachments."""
    if uid <= 0:
        raise ImapError("uid must be a positive integer.")

    conn = _connect(account)
    try:
        _select(conn, folder)
        typ, data = conn.uid("fetch", str(uid), "(RFC822.SIZE RFC822)")
        if typ != "OK":
            raise ImapError(f"UID FETCH failed: {typ} {data!r}")

        raw: bytes | None = None
        raw_size = 0
        for item in data:
            if isinstance(item, tuple) and len(item) == 2:
                meta, payload = item
                m = re.search(r"RFC822\.SIZE\s+(\d+)", meta.decode("utf-8", "replace"))
                if m:
                    raw_size = int(m.group(1))
                if payload:
                    raw = payload
                    break
        if raw is None:
            raise ImapError(
                f"Message with UID {uid} not found in folder {folder!r}."
            )

        msg = email.message_from_bytes(raw)
        headers: dict[str, str] = {}
        for key, value in msg.items():
            headers[key.lower()] = _decode_header_value(value)

        text_plain, text_html, attachments = _walk_message(msg)

        return GetMessage(
            uid=uid,
            folder=folder,
            headers=headers,
            body_text=text_plain,
            body_html=text_html,
            attachments=attachments,
            raw_size=raw_size or len(raw),
        )
    finally:
        _disconnect(conn)